#Makefile
run-dist:	#запуск приложения
	./build/install/app/bin/app
lint:
	@./gradlew checkstyleMain checkstyleTest
	
run:
	./gradlew run

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain checkstyleTest
